---
title: "journal"
author: "mz"
date: "`r format(Sys.time(), '%d.%B %Y')`"
output:
        bookdown::pdf_document2:
        toc_depth: 3
fontsize: 11pt
geometry: a4paper,left=3.5cm,right=3.5cm,top=3.5cm,bottom=4cm
header-includes:
        \usepackage{longtable}
        \usepackage{multirow}
        \usepackage{afterpage}
        \renewcommand{\contentsname}{Kazalo}
        \renewcommand{\figurename}{Slika}
        \renewcommand{\tablename}{Tabela}
urlcolor: blue
---
        
Popravki APA 6th no ampersand.

Report: zbriši "retreived from Publisher website" 

Bill: year before number, change delimiters from , to .

Konferenca: note za ime ustanove, ki jo organizira

Sicer pa je v [Zotero/styles](https://www.zotero.org/styles?q=umar)

23.6. sprejet  [pull request](https://github.com/citation-style-language/styles/pull/5520)

# 16.8.

A sem jest ta csl delala doma, zakaj ga nimam tukaj na računalniku?

[contributing](https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md) to the CSL repo. 

# 23.8.

OK, popravljam csl fajl.

Za to je fajn seznam polj in imen med zoterom in csl shemo [tukaj](https://aurimasv.github.io/z2csl/typeMap.xml)

Mendeley pa ima [visual editor](https://csl.mendeley.com/visualEditor/), ki je najboljša stvar ever. 

Potem [tukajle](https://github.com/citation-style-language/locales/blob/master/locales-sl-SI.xml) so slovenski prevodi. 

Popravila v v2:

* format datuma v `issued` je popravljen, da sta dan in mesec prav obrnjena
* format datuma v `accessed` je numeric, da ni problema s sklanjanjem
* term `issue` (ki je številka) je zdaj lowercase, da ne piše "Št." ampak "št."
* v legislation je bil simbol za `section`, sem ga vrgla ven
* editor translator text-case v lowercase (ur.)
* doi povozi url, kar je OK, se strinja Marta
* dodala vejico pred vrsto poročila (glej npr. EK 2021) in popravila kapitalizacijo. 
* vnos zakonov in drugih stvari iz uradnega lista: v polje "Public Law Number" dodaš smao številko npr. 47/2021 in v bibliografiji se izpiše "Ur. l. RS, št. 47/2021" 

* za "pridobljeno 12.2.2021" ni več vejice pred "s https..."
* dodano dvopičje za "V: zborniku.."

Vprašanja za Marto:

* v besedilu je do 5 avtorjev napisanih s priimki, 6 ali več pa idr.
* v bibliografiji jih do 7 izpiše vse, potem pa uporabi samo prvih 6 in zadnjega, vmes pa ...


# 25.8.

Še popravki:

* Vejica ven pri pravnih sodbah
* številka ("št.") ven pri descriptionih za reporte (ostane samo pri sodbah in uradnem listu)
* popravljen vrstni red v bibliografiji, da poleg imena, letnice in naslova, upošteva tudi volume, issue in številko (reporta). 


# 30.8.

še popravki:

naslov ni v italics, razen če kej knjiga ali zakon

# 13.9.2021

pri JN2021 se je pri skupinskem delu pojavilo par incidentov, ko je nek [obj] znakec se pojavil nenadoma in pri tem je nekaj besedila izginilo. 

Nataša misli, da se je to zgodilo ko je imela izklošljeno zaklepanje track changes. 

Internet pravi, da se take stvari očitno pojavljajo kadar se uporabljajo citiranja v skupnih dokumentih npr. [tukaj](https://answers.microsoft.com/en-us/msoffice/forum/all/ms-word-text-deleted-and-replaced-by-obj-boxes/b4f577dc-3780-4305-a28d-3c13f27d638c?page=2) ali pa [tukaj](https://answers.microsoft.com/en-us/msoffice/forum/all/onedrive-for-business-word-for-mac-field-codes/83d18da5-bc28-4f18-a743-219c82421bbc), ampak v obeh primerih ni rešitve, ampak bolj v smislu ne uporabljat citiranja al pa delaj lokalno. Nek predlog je bil, da je to lahko povezano z Mac-i, ampak ni prepričljivo. [Tukaj](https://answers.microsoft.com/en-us/msoffice/forum/all/little-obj-box-deleting-text-in-word/a33ada95-9e06-4dd9-b831-797706a921e9) tudi podobno. 


# 21.9.2021

popravila še ene druge urednike na lowercase.. 
pa Marti niso všeč oglati oklepaji okol descriptionov alal podatkovni portal ipd .čeprav to je APA, recimo [tukaj](https://blog.apastyle.org/apastyle/2013/12/how-to-cite-a-data-set-in-apa-style.html). al pa [tukaj](https://aut.ac.nz.libguides.com/APA7th/datasets)

# 22.9.21

OK, v oglatih oklepajih naredimo male začetnice, Marta in Špela tudi pravita, da je tko bolš. V oglatih se izpiše samo kadar je samo type. ni pa tudi report number. 

Pull request.

Ampak ne: zdej je problem, da je vejica pred oklepajem, tega se ne dela. ampak ta vejica med descriptionom in titlom je tam tudi kadar je description nekaj drugega, torej ne bracketed.. skratka gre za delimiter, ne vem, če ga znam dat ven. Slovnično pravilnejša alternativa bi bila pika. Če ne pogruntam kako jih ločit, bom dala pač piko i guess. 

Umaknila pull request

Marta ma še eno foro: pri volume-issue članku, ki nima volume-a, noče imeti vejice, ker je pred oklepajem.. OK, to sem zdej popravila. če je samo volume al pa samo issue, nima oklepajev, ločiš jih pa po italics. 

commit. 

OK, rešila vejice med report typom v oglatih oklepajih. Izjemo naredila, če imaš report in nimaš numberja in page, imaš samo report type, potem ni vejice. Glupo je, če daš strani zraven, ker pol so vejice spet nazaj, ampak kdo bo dal strani zraven. Lahko pa jih tudi skinem, če Marta reče, da je OK. 

commit. 

submit new version.

#23.9.21

odprla tabelo kratice.xlsx s seznamom kratic ipd, ki jih je treba dorečt

z Matejo eno uro popravljala njene vnose, predvsem zato, ker jih je citirala iz My Library, ne  UMAR, in potem ne delajo popravki, če si kopijo naredil, moraš pač oboje popravit.. 